spring.application.name=Ex12LoginJoinDb

#server.port=8090

# thymeleaf
spring.thymeleaf.cache=false

#JPA\uC124\uC815
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true

# \uC0AC\uC6A9\uD560 \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uC758 \uBC29\uC5B8(Dialect) \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# pretty sql format - \uC904\uBC14\uAFC8, \uCF54\uBA58\uD2B8\uB97C \uB2EC\uC544\uC90C.
spring.jpa.properties.hibernate.format_sql=true 
spring.jpa.properties.hibernate.use_sql_comments=true

# mysql(\uC624\uB77C\uD074\uC77C\uB54C\uB294 \uBC14\uAFB8\uC5B4\uC57C\uD568)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=mysql123

# logging
logging.level.org.hibernate.type.description.sql.BasicBinder=trace
logging.level.org.hibernate.SQL=debug
# Hibernate 6.1.5 updated in springboot 3.x, 4.x
logging.level.org.hibernate.orm.jdbc.bind=trace
