-- 실습 7-1
SELECT SUM(SAL)
  FROM EMP;

-- 실습 7-2
SELECT ENAME, SUM(SAL)
  FROM EMP;

-- 실습 7-3
SELECT SUM(COMM)
  FROM EMP;

-- 실습 7-4
SELECT SUM(DISTINCT SAL),
       SUM(ALL SAL),
       SUM(SAL)
  FROM EMP;

-- 실습 7-5
SELECT COUNT(*)
  FROM EMP;

-- 실습 7-6
SELECT COUNT(*)
  FROM EMP
 WHERE DEPTNO = 30;

-- 실습 7-7
SELECT COUNT(DISTINCT SAL),
       COUNT(ALL SAL),
       COUNT(SAL)
  FROM EMP;

-- 실습 7-8
SELECT COUNT(COMM)
  FROM EMP;

-- 실습 7-9
SELECT COUNT(COMM)
  FROM EMP
 WHERE COMM IS NOT NULL;

-- 실습 7-10
SELECT MAX(SAL)
  FROM EMP
 WHERE DEPTNO = 10;

-- 실습 7-11
SELECT MIN(SAL)
  FROM EMP
 WHERE DEPTNO = 10;

-- 실습 7-12
SELECT MAX(HIREDATE)
  FROM EMP
 WHERE DEPTNO = 20;

-- 실습 7-13
SELECT MIN(HIREDATE)
  FROM EMP
 WHERE DEPTNO = 20;

-- 실습 7-14
SELECT AVG(SAL)
  FROM EMP
 WHERE DEPTNO = 30;

-- 실습 7-15
SELECT AVG(DISTINCT SAL)
  FROM EMP
 WHERE DEPTNO = 30;

-- 실습 7-16
SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT AVG(SAL), '20' AS DEPTNO FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT AVG(SAL), '30' AS DEPTNO FROM EMP WHERE DEPTNO = 30;

-- 실습 7-17
SELECT AVG(SAL), DEPTNO
  FROM EMP
GROUP BY DEPTNO;

-- 실습 7-18
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- 실습 7-19
SELECT ENAME, DEPTNO, AVG(SAL)
  FROM EMP
GROUP BY DEPTNO;

-- 실습 7-20
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

-- 실습 7-21
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
 WHERE AVG(SAL) >= 2000
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- 실습 7-22
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

-- 실습 7-23
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
 WHERE SAL <= 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

