-- 실습 A-1
CREATE USER C##ORCLSTUDY
IDENTIFIED BY ORACLE;

-- 실습 A-2
ALTER SESSION SET "_oracle_script"=true;

CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

-- 실습 A-3
GRANT CREATE SESSION TO ORCLSTUDY;

-- 실습 A-4
ALTER USER ORCLSTUDY
IDENTIFIED BY ORCL;

-- 실습 A-5
DROP USER ORCLSTUDY;

-- 실습 A-6
DROP USER ORCLSTUDY CASCADE;

-- 실습 A-7
CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 실습 A-8
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

-- 실습 A-9
CREATE TABLE TEMP1 (
  COL1 VARCHAR2(20),
  COL2 VARCHAR2(20)
);

INSERT INTO TEMP1 VALUES ('USER', 'GRANT_TEST');

SELECT * FROM TEMP1;

-- 실습 A-10
REVOKE RESOURCE, CREATE TABLE FROM ORCLSTUDY;

-- 실습 A-11
CREATE TABLE TEMP2 (
 COL1 VARCHAR2(20),
 COL2 VARCHAR2(20)
);

-- 실습 A-12
CREATE TABLE TEMP(
  COL1 VARCHAR2(20),
  COL2 VARCHAR2(20)
);

GRANT SELECT ON TEMP TO ORCLSTUDY;

GRANT INSERT ON TEMP TO ORCLSTUDY;

-- 실습 A-13
GRANT SELECT, INSERT ON TEMP
 TO ORCLSTUDY;
 
-- 실습 A-14
SELECT * FROM SCOTT.TEMP;

INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCLSTUDY');

SELECT * FROM SCOTT.TEMP;

-- 실습 A-15
REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;

-- 실습 A-16
SELECT * FROM SCOTT.TEMP;

-- 실습 A-17
CREATE ROLE ROLESTUDY;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM
 TO ROLESTUDY;
 
-- 실습 A-18
GRANT ROLESTUDY TO ORCLSTUDY;

-- 실습 A-19
SELECT * FROM USER_SYS_PRIVS;

SELECT * FROM USER_ROLE_PRIVS;
 
